apiVersion: v1
kind: PersistentVolume
metadata:
  name: test2
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: localstorage
  hostPath:
    path: "/mnt/c/Users/Tmax/Desktop/업무용/minikube/shellscript/mount"
    type: DirectoryOrCreate
